---
- name: Deploy Services
  hosts: lab10-vm
  become: no
  tasks:
    - name: Clone/Pull Git Repo
      ansible.builtin.git:
        repo: git@github.com:Pauwo/ACIT3855-Lab10.git
        dest: /home/paulo/lab10
        accept_hostkey: yes
        version: main
        force: yes
        key_file: ~/.ssh/id_ed25519

    - name: Create 'data' and 'logs' directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
        owner: nobody
        group: nogroup
      loop:
        - /home/paulo/lab10/data
        - /home/paulo/lab10/logs
        - /home/paulo/lab10/data/processing
      become: true

    - name: Ensure event_stats.json has correct permissions
      ansible.builtin.file:
        path: /home/paulo/lab10/data/processing/event_stats.json
        state: touch  
        mode: "0666"  
        owner: nobody  
        group: nogroup  
      become: true


    - name: Copy all files from prod to test
      synchronize:
        src: /home/paulo/acit3855/ACIT3855-Lab10/config/prod/
        dest: /home/paulo/lab10/config/test/
        mode: push  # The push mode is for copying from the local machine to the remote server
        recursive: yes  # Ensure all files and subdirectories are copied
        delete: no 



    - name: Ensure Docker Compose is Running
      ansible.builtin.shell: |
        cd /home/paulo/lab10
        docker compose up -d --build
      args:
        executable: /bin/bash